public enum ProjectAchievement
{
	ProjectAchievementGoldenHammerOverall,
	ProjectAchievementGoldenHammerAttack,
	ProjectAchievementGoldenHammerSpeed,
	ProjectAchievementGoldenHammerAccuracy,
	ProjectAchievementGoldenHammerMagic,
	ProjectAchievementBlank
}
